### ISSUE TITLE
Polymer build; unable to optimize .js file firebase-messaging.html

### ISSUE THREAD

**Issue by cassshh** [firebase/polymerfire#141]
### Description
Polymer unable to optimize .js file `firebase-messaging.html`

### Expected outcome
```shell
$ polymer build
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
info:    Build complete!
```

### Actual outcome
```shell
$ polymer build
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
warn:    Unable to optimize .js file ...\bower_components\polymerfire\firebase-messaging.html_script_0.js
{ err:
   { message: 'SyntaxError: Unexpected token punc «(», expected punc «:»',
     filename: 0,
     line: 173,
     col: 21,
     pos: 5124,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (...\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:1545:18)\n    at js_error (eval at <anonymous> (...\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:1553:11)\n    at croak (eval at <anonymous> ...\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2092:9)\n    at token_error (eval at <anonymous> (...\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2100:9)\n    at expect_token (eval at <anonymous> (...\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2113:9)\n    at expect (eval at <anonymous> (...\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2116:36)\n    at eval (eval at <anonymous> (...\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2689:13)\n    at eval (eval at <anonymous> (...\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2139:24)\n    at expr_atom (eval at <anonymous> (...\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2619:35)\n    at maybe_unary (eval at <anonymous> (...\\AppData\\Roaming\\npm\\node_modules\\polymer-cli\\node_modules\\uglify-js\\tools\\node.js:28:1), <anonymous>:2795:19)' } }
info:    Build complete!
```

### Steps to reproduce
1. Have a project
2. Have polymerfire as dependency
3. Execute `$ bower install`
4. Execute `$ polymer build`

### Solution
In file: ```firebase-messaging.html```
Line: 239

Change :
``` javascript
_bootstrapApp(app, customSw) {
```

__To__ :
```javascript
_bootstrapApp: function(app, customSw) {
```

**Comment by tjmonsi** [comment]
This is because of line 239 in firebase-messaging.html

```
_bootstrapApp(app, customSw) {
          if (app && !customSw) {
            this.activate();
          }
        }
```

It uses an ES6 version of defining a function in an object dictionary. I could make a PR just for the sake of making it usable for the current version of polymer build.

**Comment by mbleigh** [comment]
Thanks for the PR! Fixed.
