### ISSUE TITLE
polymer-cli build fails

### ISSUE THREAD

**Issue by milesje** [firebase/polymerfire#62]
I'm not sure if this is an issue with polymerfire or with the polymer-cli build tool.
### Description

```
error:   Promise rejection: Error: no resolver found for ../../../../bower_components/firebase/firebase.js
error:   Error: no resolver found for ../../../../bower_components/firebase/firebase.js
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Object.<anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/vulcanize/lib/vulcan.js:318:26)
    at Array.map (native)
    at Object.inlineScripts (/usr/local/lib/node_modules/polymer-cli/node_modules/vulcanize/lib/vulcan.js:311:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/vulcanize/lib/vulcan.js:458:21)
    at run (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
error:   Promise rejection: Error: no resolver found for ../../../../bower_components/firebase/firebase.js
error:   Error: no resolver found for ../../../../bower_components/firebase/firebase.js
    at FileLoader.request (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Object.<anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/vulcanize/lib/vulcan.js:318:26)
    at Array.map (native)
    at Object.inlineScripts (/usr/local/lib/node_modules/polymer-cli/node_modules/vulcanize/lib/vulcan.js:311:34)
    at Object.<anonymous> (/usr/local/lib/node_modules/polymer-cli/node_modules/vulcanize/lib/vulcan.js:458:21)
    at run (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:89:22)
    at /usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/usr/local/lib/node_modules/polymer-cli/node_modules/hydrolysis/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
```
### Expected outcome

Project is build for both bundled and unbundled version.
### Actual outcome

Above error occurs during build.

**Comment by rvbyron** [comment]
I'm getting what appears to be the same issue on Windows 10; node v4.4.5; bower v1.7.9
 - Polymerfire source:
   - branch: master 
   - revision: committed at 6/25/2016 3:08 PM
```
C:\Users\JoeUser\projects\polymerfire>polymer build
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
warn:    Unable to uglify file C:\Users\JoeUser\projects\polymerfire\bower_components\note-app-elements\na-editor.html_script_0.js
warn:    Unable to uglify file C:\Users\JoeUser\projects\polymerfire\bower_components\marked-element\demo\index.html_script_0.js
warn:    Unable to uglify file C:\Users\JoeUser\projects\polymerfire\bower_components\marked-element\test\marked-element.html_script_0.js
warn:    Unable to uglify file C:\Users\JoeUser\projects\polymerfire\bower_components\marked-element\test\marked-element.html_script_1.js
warn:    Unable to uglify file C:\Users\JoeUser\projects\polymerfire\bower_components\marked-element\test\marked-element.html_script_2.js
warn:    Unable to uglify file C:\Users\JoeUser\projects\polymerfire\bower_components\marked-element\test\marked-element.html_script_3.js
warn:    Unable to uglify file C:\Users\JoeUser\projects\polymerfire\bower_components\marked-element\test\marked-element.html_script_4.js
warn:    Unable to uglify file C:\Users\JoeUser\projects\polymerfire\bower_components\web-component-tester\data\index.html_script_0.js
warn:    Unable to uglify file C:\Users\JoeUser\projects\polymerfire\bower_components\web-component-tester\data\index.html_script_2.js
warn:    Unable to uglify file C:\Users\JoeUser\projects\polymerfire\bower_components\sw-toolbox\docs\cache-expiration-options\app.js
warn:    Unable to uglify file C:\Users\JoeUser\projects\polymerfire\bower_components\sw-toolbox\docs\cache-expiration-options\service-worker.js
error:   Promise rejection: Error: no resolver found for ../polymer/polymer.html
error:   Error: no resolver found for ../polymer/polymer.html
    at FileLoader.request (C:\Users\JoeUser\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\hydrolysis\lib\loader\file-loader.js:70:37)
    at Analyzer.load (C:\Users\JoeUser\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\hydrolysis\lib\analyzer.js:121:32)
    at Analyzer._getDependencies (C:\Users\JoeUser\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\hydrolysis\lib\analyzer.js:433:25)
    at Analyzer._dependenciesLoadedFor (C:\Users\JoeUser\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\hydrolysis\lib\analyzer.js:401:25)
    at Analyzer._parseHTML (C:\Users\JoeUser\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\hydrolysis\lib\analyzer.js:227:50)
    at null._onTimeout (C:\Users\JoeUser\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\hydrolysis\lib\analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)

[ ... Deleted Log Events ... ]	
	
error:   Promise rejection: Error: no resolver found for ../firebase/firebase.js
error:   Error: no resolver found for ../firebase/firebase.js
    at FileLoader.request (C:\Users\JoeUser\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\hydrolysis\lib\loader\file-loader.js:70:37)
    at Analyzer._processScript (C:\Users\JoeUser\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\hydrolysis\lib\analyzer.js:378:36)
    at C:\Users\JoeUser\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\hydrolysis\lib\analyzer.js:301:44
    at Array.forEach (native)
    at Analyzer._processScripts (C:\Users\JoeUser\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\hydrolysis\lib\analyzer.js:300:21)
    at Analyzer._parseHTML (C:\Users\JoeUser\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\hydrolysis\lib\analyzer.js:161:39)
    at null._onTimeout (C:\Users\JoeUser\AppData\Roaming\npm\node_modules\polymer-cli\node_modules\hydrolysis\lib\analyzer.js:125:39)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by rvbyron** [comment]
Here is the complete list of errors only without the stack trace. They appeared to be duplicates of the same one and I deleted those events in the previous comment. Most all the errors were complaining that polymer was missing and one for firebase.js, yet if I go into the bower components directory, I find /polymer/polymer.html and firebase/firebase.js exist. I am executing my `polymer build` command from the polymerfire root directory.
```
error:   Promise rejection: Error: no resolver found for ../polymer/polymer.html
error:   Error: no resolver found for ../polymer/polymer.html
error:   Promise rejection: Error: no resolver found for ../polymer/polymer.html
error:   Error: no resolver found for ../polymer/polymer.html
error:   Promise rejection: Error: no resolver found for ../polymer/polymer.html
error:   Error: no resolver found for ../polymer/polymer.html
error:   Promise rejection: Error: no resolver found for ../polymer/polymer.html
error:   Error: no resolver found for ../polymer/polymer.html
error:   Promise rejection: Error: no resolver found for ../polymer/polymer.html
error:   Error: no resolver found for ../polymer/polymer.html
error:   Promise rejection: Error: no resolver found for ../polymer/polymer.html
error:   Error: no resolver found for ../polymer/polymer.html
error:   Promise rejection: Error: no resolver found for ../polymer/polymer.html
error:   Error: no resolver found for ../polymer/polymer.html
error:   Promise rejection: Error: no resolver found for ../polymer/polymer.html
error:   Error: no resolver found for ../polymer/polymer.html
error:   Promise rejection: Error: no resolver found for ../polymer/polymer.html
error:   Error: no resolver found for ../polymer/polymer.html
error:   Promise rejection: Error: no resolver found for ../firebase/firebase.js
error:   Error: no resolver found for ../firebase/firebase.js
```

**Comment by TheoMer** [comment]
I'm also experiencing this very same issue. Is there an eta for resolving this?

**Comment by mbleigh** [comment]
Would you folks mind filing a bug and describing the issue on the polymer-cli repo? I can't think of anything specific to PolymerFire that would be causing this. I'll leave the bug open until it's fixed, though.

**Comment by rvbyron** [comment]
@mbleigh Does that mean that you are seeing the same results or not? 
Could you post your versions of OS, Node, Polymer
node --version
polymer --version

I am running MS Windows 10, polymer 0.12.0 and node v4.4.5.

Thanks!

**Comment by milesje** [comment]
I am on Mac OS X 10.11.5
node version: 4.4.5
polymer version: 0.11.1

**Comment by rvbyron** [comment]
Can anyone out there successfully build the firebase/polymerfire library?
If so, can you upload your versions of OS, node, polymer, and bower?

Cheers!
Bob

**Comment by dsnowdon** [comment]
Same here

**Comment by dsnowdon** [comment]
Same issue here

OSX: 10.11.4
node: 3.9.0
Polymer/polymer#^1.4.0

**Comment by dmix007** [comment]
Same here.  I'm on Linux Mint 18 (Sarah)
Node 6.2.2
Polymer 0.12.0
I started by running the shell app "polymer init" and selected the "application: A blank application template" option.  I then made minor changes to use firebase-app and firebase-document elements.

Errors below:
### info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
warn:    Unable to uglify file /home/mixd/Desktop/buildUp_1_FBLogin/bower_components/marked-element/demo/index.html_script_0.js
warn:    Unable to uglify file /home/mixd/Desktop/buildUp_1_FBLogin/bower_components/marked-element/test/marked-element.html_script_0.js
warn:    Unable to uglify file /home/mixd/Desktop/buildUp_1_FBLogin/bower_components/marked-element/test/marked-element.html_script_1.js
warn:    Unable to uglify file /home/mixd/Desktop/buildUp_1_FBLogin/bower_components/marked-element/test/marked-element.html_script_2.js
warn:    Unable to uglify file /home/mixd/Desktop/buildUp_1_FBLogin/bower_components/marked-element/test/marked-element.html_script_3.js
warn:    Unable to uglify file /home/mixd/Desktop/buildUp_1_FBLogin/bower_components/marked-element/test/marked-element.html_script_4.js
warn:    Unable to uglify file /home/mixd/Desktop/buildUp_1_FBLogin/bower_components/web-component-tester/data/index.html_script_0.js
warn:    Unable to uglify file /home/mixd/Desktop/buildUp_1_FBLogin/bower_components/web-component-tester/data/index.html_script_2.js
error:   Promise rejection: Error: no resolver found for ../../../../bower_components/firebase/firebase.js
error:   Error: no resolver found for ../../../../bower_components/firebase/firebase.js
    at FileLoader.request (/usr/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Object.<anonymous> (/usr/lib/node_modules/polymer-cli/node_modules/vulcanize/lib/vulcan.js:318:26)
    at Array.map (native)
    at Object.inlineScripts (/usr/lib/node_modules/polymer-cli/node_modules/vulcanize/lib/vulcan.js:311:34)
    at Object.<anonymous> (/usr/lib/node_modules/polymer-cli/node_modules/vulcanize/lib/vulcan.js:458:21)
    at run (/usr/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:89:22)
    at /usr/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/usr/lib/node_modules/polymer-cli/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
error:   Promise rejection: Error: no resolver found for ../../../../bower_components/firebase/firebase.js
error:   Error: no resolver found for ../../../../bower_components/firebase/firebase.js
    at FileLoader.request (/usr/lib/node_modules/polymer-cli/node_modules/hydrolysis/lib/loader/file-loader.js:70:37)
    at Object.<anonymous> (/usr/lib/node_modules/polymer-cli/node_modules/vulcanize/lib/vulcan.js:318:26)
    at Array.map (native)
    at Object.inlineScripts (/usr/lib/node_modules/polymer-cli/node_modules/vulcanize/lib/vulcan.js:311:34)
    at Object.<anonymous> (/usr/lib/node_modules/polymer-cli/node_modules/vulcanize/lib/vulcan.js:458:21)
    at run (/usr/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:89:22)
    at /usr/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:102:28
    at flush (/usr/lib/node_modules/polymer-cli/node_modules/core-js/modules/_microtask.js:18:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by ziszo** [comment]
Node: 4.2.6
Polymer-CLI: 0.12.0

![image](https://cloud.githubusercontent.com/assets/4342864/16869236/7252c3a0-4aae-11e6-8a3a-9067e245c3f7.png)

**Comment by joeblew99** [comment]
why is everyone on a superold version of node ?

curious if i am doing something wrong by being on 6.3

**Comment by amadeoas** [comment]
It happens to me too with

OSX: 10.10.5
node: 6.3.1
polymer-cli: 0.12.0
polymer: 1.6.0

except for OSX the others are all the latest version for their respective packages

**Comment by tjmonsi** [comment]
Given that there's no activity for more than 6 months, we'll close this issue for now. Please feel free to re-open this if it hasn't been resolved
